# Generated by Django 2.2.5 on 2019-09-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
